// Real teams and players — 2025-26 English Premier League.
// Player format: [name, pos, age, ovr, pot, nationality]
// Ratings are on a 0-99 scale (BBGM-style). Ages as of the start of the 2025-26 season.
// Squads reflect the summer 2025 transfer window. Each squad is topped up with
// generated academy depth at league init so every club has a full roster.

const START_SEASON = 2025;

const REAL_TEAMS = [
  {
    name: "Arsenal", abbrev: "ARS", stadium: "Emirates Stadium", colors: ["#EF0107", "#FFFFFF"], stature: 5, budget: 110,
    players: [
      ["Bukayo Saka", "RW", 23, 88, 92, "England"],
      ["Martin Ødegaard", "AM", 26, 87, 88, "Norway"],
      ["Declan Rice", "DM", 26, 87, 89, "England"],
      ["William Saliba", "CB", 24, 87, 90, "France"],
      ["Gabriel Magalhães", "CB", 27, 86, 87, "Brazil"],
      ["Viktor Gyökeres", "ST", 27, 85, 87, "Sweden"],
      ["Martín Zubimendi", "DM", 26, 85, 87, "Spain"],
      ["David Raya", "GK", 29, 85, 86, "Spain"],
      ["Eberechi Eze", "AM", 27, 84, 85, "England"],
      ["Jurriën Timber", "RB", 24, 84, 87, "Netherlands"],
      ["Kai Havertz", "ST", 26, 83, 84, "Germany"],
      ["Gabriel Martinelli", "LW", 24, 83, 85, "Brazil"],
      ["Leandro Trossard", "LW", 30, 82, 82, "Belgium"],
      ["Ben White", "RB", 27, 82, 83, "England"],
      ["Riccardo Calafiori", "LB", 23, 82, 86, "Italy"],
      ["Noni Madueke", "RW", 23, 81, 85, "England"],
      ["Gabriel Jesus", "ST", 28, 80, 80, "Brazil"],
      ["Mikel Merino", "CM", 29, 80, 80, "Spain"],
      ["Christian Nørgaard", "DM", 31, 78, 78, "Denmark"],
      ["Cristhian Mosquera", "CB", 21, 78, 86, "Spain"],
      ["Myles Lewis-Skelly", "LB", 18, 78, 89, "England"],
      ["Ethan Nwaneri", "AM", 18, 77, 90, "England"],
      ["Kepa Arrizabalaga", "GK", 30, 77, 77, "Spain"],
    ],
  },
  {
    name: "Aston Villa", abbrev: "AVL", stadium: "Villa Park", colors: ["#95BFE5", "#670E36"], stature: 4, budget: 60,
    players: [
      ["Emiliano Martínez", "GK", 32, 85, 85, "Argentina"],
      ["Morgan Rogers", "AM", 23, 83, 88, "England"],
      ["Ollie Watkins", "ST", 29, 83, 83, "England"],
      ["Pau Torres", "CB", 28, 83, 83, "Spain"],
      ["Youri Tielemans", "CM", 28, 82, 82, "Belgium"],
      ["Amadou Onana", "DM", 23, 81, 86, "Belgium"],
      ["Ezri Konsa", "CB", 27, 81, 82, "England"],
      ["Boubacar Kamara", "DM", 25, 81, 83, "France"],
      ["John McGinn", "CM", 30, 80, 80, "Scotland"],
      ["Jadon Sancho", "LW", 25, 79, 81, "England"],
      ["Matty Cash", "RB", 28, 79, 79, "Poland"],
      ["Tyrone Mings", "CB", 32, 79, 79, "England"],
      ["Donyell Malen", "RW", 26, 78, 79, "Netherlands"],
      ["Lucas Digne", "LB", 32, 78, 78, "France"],
      ["Evann Guessand", "ST", 24, 78, 83, "Ivory Coast"],
      ["Ian Maatsen", "LB", 23, 78, 84, "Netherlands"],
      ["Emiliano Buendía", "AM", 28, 77, 77, "Argentina"],
      ["Lamare Bogarde", "DM", 21, 74, 82, "Netherlands"],
      ["Marco Bizot", "GK", 34, 74, 74, "Netherlands"],
    ],
  },
  {
    name: "Bournemouth", abbrev: "BOU", stadium: "Vitality Stadium", colors: ["#DA291C", "#000000"], stature: 3, budget: 45,
    players: [
      ["Antoine Semenyo", "LW", 25, 83, 87, "Ghana"],
      ["Justin Kluivert", "AM", 26, 81, 83, "Netherlands"],
      ["Evanilson", "ST", 25, 79, 84, "Brazil"],
      ["Marcos Senesi", "CB", 28, 79, 79, "Argentina"],
      ["Đorđe Petrović", "GK", 25, 79, 84, "Serbia"],
      ["Ryan Christie", "CM", 30, 78, 78, "Scotland"],
      ["Lewis Cook", "DM", 28, 78, 78, "England"],
      ["Tyler Adams", "DM", 26, 78, 79, "USA"],
      ["David Brooks", "RW", 28, 77, 77, "Wales"],
      ["Marcus Tavernier", "LW", 26, 77, 78, "England"],
      ["Adrien Truffert", "LB", 23, 77, 83, "France"],
      ["Amine Adli", "LW", 25, 77, 80, "Morocco"],
      ["Bafodé Diakité", "CB", 24, 76, 84, "France"],
      ["Alex Scott", "CM", 21, 76, 83, "England"],
      ["Enes Ünal", "ST", 28, 75, 75, "Turkey"],
      ["Álex Jiménez", "RB", 20, 75, 83, "Spain"],
      ["Adam Smith", "RB", 34, 72, 72, "England"],
      ["Will Dennis", "GK", 24, 68, 72, "England"],
    ],
  },
  {
    name: "Brentford", abbrev: "BRE", stadium: "Gtech Community Stadium", colors: ["#E30613", "#FBB800"], stature: 2, budget: 45,
    players: [
      ["Caoimhín Kelleher", "GK", 26, 80, 84, "Ireland"],
      ["Igor Thiago", "ST", 24, 79, 85, "Brazil"],
      ["Kevin Schade", "LW", 23, 79, 84, "Germany"],
      ["Mikkel Damsgaard", "AM", 25, 79, 80, "Denmark"],
      ["Nathan Collins", "CB", 24, 79, 83, "Ireland"],
      ["Keane Lewis-Potter", "LW", 24, 78, 80, "England"],
      ["Dango Ouattara", "RW", 23, 77, 83, "Burkina Faso"],
      ["Vitaly Janelt", "CM", 27, 77, 77, "Germany"],
      ["Ethan Pinnock", "CB", 32, 77, 77, "England"],
      ["Kristoffer Ajer", "CB", 27, 76, 76, "Norway"],
      ["Yehor Yarmoliuk", "CM", 21, 76, 84, "Ukraine"],
      ["Fábio Carvalho", "AM", 22, 76, 82, "Portugal"],
      ["Michael Kayode", "RB", 21, 76, 84, "Italy"],
      ["Antoni Milambo", "CM", 20, 75, 84, "Netherlands"],
      ["Jordan Henderson", "DM", 35, 75, 75, "England"],
      ["Aaron Hickey", "LB", 23, 75, 79, "Scotland"],
      ["Sepp van den Berg", "CB", 23, 75, 80, "Netherlands"],
      ["Rico Henry", "LB", 28, 74, 74, "England"],
      ["Hákon Valdimarsson", "GK", 23, 71, 77, "Iceland"],
    ],
  },
  {
    name: "Brighton & Hove Albion", abbrev: "BHA", stadium: "Amex Stadium", colors: ["#0057B8", "#FFCD00"], stature: 3, budget: 55,
    players: [
      ["Kaoru Mitoma", "LW", 28, 83, 84, "Japan"],
      ["Carlos Baleba", "DM", 21, 81, 89, "Cameroon"],
      ["Bart Verbruggen", "GK", 22, 80, 86, "Netherlands"],
      ["Georginio Rutter", "AM", 23, 79, 84, "France"],
      ["Yankuba Minteh", "RW", 21, 79, 86, "Gambia"],
      ["Jan Paul van Hecke", "CB", 25, 79, 83, "Netherlands"],
      ["Danny Welbeck", "ST", 34, 78, 78, "England"],
      ["Lewis Dunk", "CB", 33, 78, 78, "England"],
      ["Ferdi Kadıoğlu", "LB", 25, 78, 80, "Turkey"],
      ["Mats Wieffer", "DM", 25, 78, 80, "Netherlands"],
      ["Joël Veltman", "RB", 33, 76, 76, "Netherlands"],
      ["Yasin Ayari", "CM", 21, 77, 84, "Sweden"],
      ["Jack Hinshelwood", "CM", 20, 76, 84, "England"],
      ["Brajan Gruda", "RW", 21, 75, 84, "Germany"],
      ["Maxim De Cuyper", "LB", 24, 77, 82, "Belgium"],
      ["Diego Gómez", "CM", 22, 76, 83, "Paraguay"],
      ["Olivier Boscagli", "CB", 27, 77, 78, "France"],
      ["Stefanos Tzimas", "ST", 19, 74, 85, "Greece"],
      ["Charalampos Kostoulas", "ST", 18, 72, 84, "Greece"],
      ["Jason Steele", "GK", 34, 72, 72, "England"],
    ],
  },
  {
    name: "Burnley", abbrev: "BUR", stadium: "Turf Moor", colors: ["#6C1D45", "#99D6EA"], stature: 1, budget: 30,
    players: [
      ["Kyle Walker", "RB", 35, 77, 77, "England"],
      ["Martin Dúbravka", "GK", 36, 76, 76, "Slovakia"],
      ["Jaidon Anthony", "LW", 25, 75, 77, "England"],
      ["Lyle Foster", "ST", 24, 74, 78, "South Africa"],
      ["Maxime Estève", "CB", 23, 75, 82, "France"],
      ["Zian Flemming", "ST", 27, 74, 75, "Netherlands"],
      ["Josh Cullen", "CM", 29, 74, 74, "Ireland"],
      ["Hannibal Mejbri", "CM", 22, 74, 80, "Tunisia"],
      ["Quilindschy Hartman", "LB", 23, 75, 81, "Netherlands"],
      ["Lesley Ugochukwu", "DM", 21, 74, 82, "France"],
      ["Loum Tchaouna", "RW", 21, 74, 81, "France"],
      ["Jacob Bruun Larsen", "LW", 26, 75, 75, "Denmark"],
      ["Marcus Edwards", "RW", 26, 74, 75, "England"],
      ["Bashir Humphreys", "CB", 22, 74, 80, "England"],
      ["Armando Broja", "ST", 23, 74, 79, "Albania"],
      ["Connor Roberts", "RB", 29, 72, 72, "Wales"],
      ["Hjalmar Ekdal", "CB", 26, 72, 73, "Sweden"],
      ["Josh Laurent", "CM", 30, 72, 72, "England"],
      ["Vaclav Hladky", "GK", 34, 71, 71, "Czech Republic"],
    ],
  },
  {
    name: "Chelsea", abbrev: "CHE", stadium: "Stamford Bridge", colors: ["#034694", "#FFFFFF"], stature: 5, budget: 120,
    players: [
      ["Cole Palmer", "AM", 23, 89, 92, "England"],
      ["Moisés Caicedo", "DM", 23, 87, 90, "Ecuador"],
      ["Enzo Fernández", "CM", 24, 85, 87, "Argentina"],
      ["João Pedro", "ST", 23, 84, 88, "Brazil"],
      ["Marc Cucurella", "LB", 27, 84, 84, "Spain"],
      ["Reece James", "RB", 25, 84, 85, "England"],
      ["Levi Colwill", "CB", 22, 83, 88, "England"],
      ["Pedro Neto", "RW", 25, 82, 83, "Portugal"],
      ["Alejandro Garnacho", "LW", 21, 82, 88, "Argentina"],
      ["Robert Sánchez", "GK", 27, 80, 80, "Spain"],
      ["Estêvão", "RW", 18, 80, 92, "Brazil"],
      ["Jamie Gittens", "LW", 21, 80, 87, "England"],
      ["Malo Gusto", "RB", 22, 80, 85, "France"],
      ["Trevoh Chalobah", "CB", 26, 80, 80, "England"],
      ["Wesley Fofana", "CB", 24, 80, 83, "France"],
      ["Liam Delap", "ST", 22, 79, 86, "England"],
      ["Roméo Lavia", "DM", 21, 79, 86, "Belgium"],
      ["Andrey Santos", "CM", 21, 77, 85, "Brazil"],
      ["Benoît Badiashile", "CB", 24, 78, 80, "France"],
      ["Tosin Adarabioyo", "CB", 27, 78, 78, "England"],
      ["Filip Jørgensen", "GK", 23, 76, 82, "Denmark"],
      ["Tyrique George", "LW", 19, 74, 84, "England"],
    ],
  },
  {
    name: "Crystal Palace", abbrev: "CRY", stadium: "Selhurst Park", colors: ["#1B458F", "#C4122E"], stature: 3, budget: 40,
    players: [
      ["Marc Guéhi", "CB", 25, 84, 86, "England"],
      ["Jean-Philippe Mateta", "ST", 28, 81, 81, "France"],
      ["Daniel Muñoz", "RB", 29, 81, 81, "Colombia"],
      ["Adam Wharton", "DM", 21, 80, 88, "England"],
      ["Ismaïla Sarr", "RW", 27, 80, 80, "Senegal"],
      ["Dean Henderson", "GK", 28, 80, 80, "England"],
      ["Maxence Lacroix", "CB", 25, 80, 82, "France"],
      ["Tyrick Mitchell", "LB", 25, 79, 80, "England"],
      ["Yeremy Pino", "LW", 22, 78, 84, "Spain"],
      ["Daichi Kamada", "AM", 28, 78, 78, "Japan"],
      ["Chris Richards", "CB", 25, 77, 79, "USA"],
      ["Will Hughes", "CM", 30, 77, 77, "England"],
      ["Jefferson Lerma", "DM", 30, 77, 77, "Colombia"],
      ["Eddie Nketiah", "ST", 26, 77, 77, "England"],
      ["Christantus Uche", "AM", 22, 75, 82, "Nigeria"],
      ["Justin Devenny", "CM", 21, 73, 80, "Ireland"],
      ["Nathaniel Clyne", "RB", 34, 71, 71, "England"],
      ["Walter Benítez", "GK", 32, 76, 76, "Argentina"],
      ["Caleb Kporha", "RB", 18, 68, 80, "England"],
    ],
  },
  {
    name: "Everton", abbrev: "EVE", stadium: "Hill Dickinson Stadium", colors: ["#003399", "#FFFFFF"], stature: 3, budget: 45,
    players: [
      ["Jordan Pickford", "GK", 31, 84, 84, "England"],
      ["Jack Grealish", "LW", 29, 82, 82, "England"],
      ["Jarrad Branthwaite", "CB", 23, 82, 88, "England"],
      ["Iliman Ndiaye", "LW", 25, 80, 83, "Senegal"],
      ["James Tarkowski", "CB", 32, 80, 80, "England"],
      ["Idrissa Gueye", "DM", 35, 78, 78, "Senegal"],
      ["Kiernan Dewsbury-Hall", "CM", 26, 78, 79, "England"],
      ["Vitaliy Mykolenko", "LB", 26, 78, 78, "Ukraine"],
      ["James Garner", "CM", 24, 78, 80, "England"],
      ["Jake O'Brien", "CB", 24, 78, 81, "Ireland"],
      ["Thierno Barry", "ST", 22, 76, 84, "France"],
      ["Beto", "ST", 27, 77, 77, "Portugal"],
      ["Carlos Alcaraz", "AM", 22, 77, 83, "Argentina"],
      ["Merlin Röhl", "CM", 23, 75, 83, "Germany"],
      ["Dwight McNeil", "LW", 25, 77, 78, "England"],
      ["Michael Keane", "CB", 32, 75, 75, "England"],
      ["Nathan Patterson", "RB", 23, 75, 78, "Scotland"],
      ["Séamus Coleman", "RB", 36, 71, 71, "Ireland"],
      ["Mark Travers", "GK", 26, 73, 74, "Ireland"],
      ["Tyler Dibling", "RW", 19, 74, 86, "England"],
    ],
  },
  {
    name: "Fulham", abbrev: "FUL", stadium: "Craven Cottage", colors: ["#FFFFFF", "#000000"], stature: 2, budget: 40,
    players: [
      ["Bernd Leno", "GK", 33, 80, 80, "Germany"],
      ["Antonee Robinson", "LB", 27, 80, 81, "USA"],
      ["Alex Iwobi", "LW", 29, 79, 79, "Nigeria"],
      ["Calvin Bassey", "CB", 25, 79, 82, "Nigeria"],
      ["Joachim Andersen", "CB", 29, 79, 79, "Denmark"],
      ["Raúl Jiménez", "ST", 34, 78, 78, "Mexico"],
      ["Emile Smith Rowe", "AM", 25, 78, 79, "England"],
      ["Harry Wilson", "RW", 28, 78, 78, "Wales"],
      ["Rodrigo Muniz", "ST", 24, 78, 82, "Brazil"],
      ["Sander Berge", "DM", 27, 78, 78, "Norway"],
      ["Sasa Lukic", "CM", 29, 77, 77, "Serbia"],
      ["Kenny Tete", "RB", 29, 77, 77, "Netherlands"],
      ["Timothy Castagne", "RB", 29, 77, 77, "Belgium"],
      ["Kevin", "LW", 22, 76, 84, "Brazil"],
      ["Samuel Chukwueze", "RW", 26, 76, 78, "Nigeria"],
      ["Tom Cairney", "CM", 34, 75, 75, "Scotland"],
      ["Ryan Sessegnon", "LB", 25, 76, 77, "England"],
      ["Joshua King", "AM", 18, 73, 85, "England"],
      ["Issa Diop", "CB", 28, 76, 76, "France"],
      ["Benjamin Lecomte", "GK", 34, 73, 73, "France"],
    ],
  },
  {
    name: "Leeds United", abbrev: "LEE", stadium: "Elland Road", colors: ["#FFFFFF", "#1D428A"], stature: 2, budget: 40,
    players: [
      ["Anton Stach", "CM", 26, 77, 78, "Germany"],
      ["Dominic Calvert-Lewin", "ST", 28, 77, 77, "England"],
      ["Jaka Bijol", "CB", 26, 77, 78, "Slovenia"],
      ["Daniel James", "RW", 27, 77, 77, "Wales"],
      ["Ethan Ampadu", "DM", 24, 76, 79, "Wales"],
      ["Wilfried Gnonto", "LW", 21, 76, 82, "Italy"],
      ["Pascal Struijk", "CB", 25, 76, 78, "Netherlands"],
      ["Sean Longstaff", "CM", 27, 76, 76, "England"],
      ["Noah Okafor", "LW", 25, 76, 78, "Switzerland"],
      ["Joe Rodon", "CB", 27, 76, 76, "Wales"],
      ["Lucas Perri", "GK", 27, 76, 79, "Brazil"],
      ["Brenden Aaronson", "AM", 24, 76, 77, "USA"],
      ["Ao Tanaka", "CM", 26, 76, 77, "Japan"],
      ["Joel Piroe", "ST", 26, 76, 76, "Netherlands"],
      ["Jayden Bogle", "RB", 24, 75, 77, "England"],
      ["Gabriel Gudmundsson", "LB", 26, 75, 76, "Sweden"],
      ["Lukas Nmecha", "ST", 26, 75, 75, "Germany"],
      ["Ilia Gruev", "DM", 25, 75, 77, "Bulgaria"],
      ["Karl Darlow", "GK", 34, 72, 72, "England"],
    ],
  },
  {
    name: "Liverpool", abbrev: "LIV", stadium: "Anfield", colors: ["#C8102E", "#F6EB61"], stature: 5, budget: 110,
    players: [
      ["Mohamed Salah", "RW", 33, 91, 91, "Egypt"],
      ["Virgil van Dijk", "CB", 34, 89, 89, "Netherlands"],
      ["Alisson", "GK", 32, 88, 88, "Brazil"],
      ["Florian Wirtz", "AM", 22, 88, 92, "Germany"],
      ["Alexander Isak", "ST", 25, 88, 91, "Sweden"],
      ["Alexis Mac Allister", "CM", 26, 87, 88, "Argentina"],
      ["Ryan Gravenberch", "DM", 23, 86, 89, "Netherlands"],
      ["Ibrahima Konaté", "CB", 26, 85, 87, "France"],
      ["Dominik Szoboszlai", "CM", 24, 84, 86, "Hungary"],
      ["Cody Gakpo", "LW", 26, 84, 85, "Netherlands"],
      ["Hugo Ekitiké", "ST", 23, 83, 88, "France"],
      ["Jeremie Frimpong", "RB", 24, 82, 85, "Netherlands"],
      ["Milos Kerkez", "LB", 21, 81, 86, "Hungary"],
      ["Andrew Robertson", "LB", 31, 81, 81, "Scotland"],
      ["Conor Bradley", "RB", 22, 79, 86, "Ireland"],
      ["Curtis Jones", "CM", 24, 79, 81, "England"],
      ["Federico Chiesa", "RW", 27, 79, 79, "Italy"],
      ["Giorgi Mamardashvili", "GK", 24, 80, 85, "Georgia"],
      ["Wataru Endo", "DM", 32, 77, 77, "Japan"],
      ["Giovanni Leoni", "CB", 18, 75, 87, "Italy"],
      ["Rio Ngumoha", "LW", 17, 72, 88, "England"],
    ],
  },
  {
    name: "Manchester City", abbrev: "MCI", stadium: "Etihad Stadium", colors: ["#6CABDD", "#FFFFFF"], stature: 5, budget: 120,
    players: [
      ["Erling Haaland", "ST", 25, 92, 93, "Norway"],
      ["Rodri", "DM", 29, 90, 90, "Spain"],
      ["Gianluigi Donnarumma", "GK", 26, 89, 90, "Italy"],
      ["Phil Foden", "AM", 25, 86, 88, "England"],
      ["Rúben Dias", "CB", 28, 86, 86, "Portugal"],
      ["Bernardo Silva", "CM", 30, 85, 85, "Portugal"],
      ["Josko Gvardiol", "LB", 23, 85, 88, "Croatia"],
      ["Jérémy Doku", "LW", 23, 84, 87, "Belgium"],
      ["Omar Marmoush", "ST", 26, 84, 85, "Egypt"],
      ["Tijjani Reijnders", "CM", 26, 84, 85, "Netherlands"],
      ["Rayan Cherki", "AM", 21, 82, 88, "France"],
      ["John Stones", "CB", 31, 83, 83, "England"],
      ["Savinho", "RW", 21, 81, 86, "Brazil"],
      ["Nathan Aké", "CB", 30, 81, 81, "Netherlands"],
      ["Matheus Nunes", "RB", 27, 79, 80, "Portugal"],
      ["Rayan Aït-Nouri", "LB", 24, 81, 84, "Algeria"],
      ["Nico González", "DM", 23, 80, 84, "Spain"],
      ["Nico O'Reilly", "LB", 20, 78, 87, "England"],
      ["Abdukodir Khusanov", "CB", 21, 78, 85, "Uzbekistan"],
      ["Oscar Bobb", "RW", 22, 77, 84, "Norway"],
      ["James Trafford", "GK", 22, 78, 84, "England"],
      ["Rico Lewis", "RB", 20, 78, 85, "England"],
    ],
  },
  {
    name: "Manchester United", abbrev: "MUN", stadium: "Old Trafford", colors: ["#DA291C", "#FBE122"], stature: 5, budget: 100,
    players: [
      ["Bruno Fernandes", "AM", 30, 87, 87, "Portugal"],
      ["Bryan Mbeumo", "RW", 25, 84, 85, "Cameroon"],
      ["Matheus Cunha", "ST", 26, 84, 85, "Brazil"],
      ["Lisandro Martínez", "CB", 27, 83, 84, "Argentina"],
      ["Matthijs de Ligt", "CB", 25, 83, 84, "Netherlands"],
      ["Benjamin Sesko", "ST", 22, 82, 89, "Slovenia"],
      ["Amad Diallo", "RW", 23, 81, 87, "Ivory Coast"],
      ["Casemiro", "DM", 33, 81, 81, "Brazil"],
      ["Noussair Mazraoui", "RB", 27, 80, 81, "Morocco"],
      ["Manuel Ugarte", "DM", 24, 80, 82, "Uruguay"],
      ["Diogo Dalot", "RB", 26, 80, 80, "Portugal"],
      ["Kobbie Mainoo", "CM", 20, 79, 88, "England"],
      ["Leny Yoro", "CB", 19, 79, 89, "France"],
      ["Mason Mount", "AM", 26, 78, 79, "England"],
      ["Joshua Zirkzee", "ST", 24, 78, 80, "Netherlands"],
      ["Luke Shaw", "LB", 30, 78, 78, "England"],
      ["Patrick Dorgu", "LB", 20, 76, 84, "Denmark"],
      ["Harry Maguire", "CB", 32, 78, 78, "England"],
      ["Senne Lammens", "GK", 23, 77, 85, "Belgium"],
      ["Altay Bayindir", "GK", 27, 76, 77, "Turkey"],
      ["Chido Obi", "ST", 17, 70, 86, "Denmark"],
    ],
  },
  {
    name: "Newcastle United", abbrev: "NEW", stadium: "St James' Park", colors: ["#241F20", "#FFFFFF"], stature: 4, budget: 90,
    players: [
      ["Bruno Guimarães", "CM", 27, 86, 87, "Brazil"],
      ["Sandro Tonali", "DM", 25, 85, 87, "Italy"],
      ["Anthony Gordon", "LW", 24, 84, 86, "England"],
      ["Sven Botman", "CB", 25, 82, 84, "Netherlands"],
      ["Joelinton", "CM", 29, 82, 82, "Brazil"],
      ["Nick Pope", "GK", 33, 81, 81, "England"],
      ["Nick Woltemade", "ST", 23, 80, 86, "Germany"],
      ["Yoane Wissa", "ST", 28, 80, 80, "DR Congo"],
      ["Tino Livramento", "RB", 22, 80, 86, "England"],
      ["Lewis Hall", "LB", 20, 80, 86, "England"],
      ["Harvey Barnes", "LW", 27, 80, 80, "England"],
      ["Anthony Elanga", "RW", 23, 79, 84, "Sweden"],
      ["Malick Thiaw", "CB", 23, 80, 84, "Germany"],
      ["Fabian Schär", "CB", 33, 79, 79, "Switzerland"],
      ["Dan Burn", "CB", 33, 79, 79, "England"],
      ["Kieran Trippier", "RB", 34, 78, 78, "England"],
      ["Aaron Ramsdale", "GK", 27, 78, 79, "England"],
      ["Jacob Murphy", "RW", 30, 77, 77, "England"],
      ["Joe Willock", "CM", 25, 77, 78, "England"],
      ["Lewis Miley", "CM", 19, 74, 85, "England"],
      ["William Osula", "ST", 21, 73, 81, "Denmark"],
    ],
  },
  {
    name: "Nottingham Forest", abbrev: "NFO", stadium: "City Ground", colors: ["#DD0000", "#FFFFFF"], stature: 3, budget: 50,
    players: [
      ["Morgan Gibbs-White", "AM", 25, 82, 84, "England"],
      ["Murillo", "CB", 23, 82, 88, "Brazil"],
      ["Nikola Milenković", "CB", 27, 82, 82, "Serbia"],
      ["Matz Sels", "GK", 33, 80, 80, "Belgium"],
      ["Chris Wood", "ST", 33, 79, 79, "New Zealand"],
      ["Elliot Anderson", "CM", 22, 79, 86, "England"],
      ["Ola Aina", "RB", 28, 79, 79, "Nigeria"],
      ["Dan Ndoye", "RW", 24, 78, 83, "Switzerland"],
      ["Callum Hudson-Odoi", "LW", 24, 78, 79, "England"],
      ["Oleksandr Zinchenko", "LB", 28, 78, 78, "Ukraine"],
      ["Nicolás Domínguez", "CM", 27, 77, 77, "Argentina"],
      ["Igor Jesus", "ST", 24, 77, 80, "Brazil"],
      ["Neco Williams", "LB", 24, 77, 79, "Wales"],
      ["Douglas Luiz", "CM", 27, 77, 78, "Brazil"],
      ["Arnaud Kalimuendo", "ST", 23, 77, 82, "France"],
      ["Ibrahim Sangaré", "DM", 27, 76, 77, "Ivory Coast"],
      ["Omari Hutchinson", "RW", 21, 76, 83, "England"],
      ["Nicolò Savona", "RB", 22, 75, 82, "Italy"],
      ["Morato", "CB", 24, 75, 78, "Brazil"],
      ["John Victor", "GK", 29, 74, 74, "Brazil"],
      ["Taiwo Awoniyi", "ST", 27, 76, 76, "Nigeria"],
    ],
  },
  {
    name: "Sunderland", abbrev: "SUN", stadium: "Stadium of Light", colors: ["#EB172B", "#FFFFFF"], stature: 2, budget: 45,
    players: [
      ["Granit Xhaka", "DM", 32, 79, 79, "Switzerland"],
      ["Nordi Mukiele", "RB", 27, 77, 77, "France"],
      ["Habib Diarra", "CM", 21, 76, 83, "Senegal"],
      ["Simon Adingra", "LW", 23, 76, 82, "Ivory Coast"],
      ["Enzo Le Fée", "AM", 25, 76, 78, "France"],
      ["Omar Alderete", "CB", 28, 75, 75, "Paraguay"],
      ["Lutsharel Geertruida", "CB", 25, 76, 79, "Netherlands"],
      ["Reinildo Mandava", "LB", 31, 74, 74, "Mozambique"],
      ["Bertrand Traoré", "RW", 29, 74, 74, "Burkina Faso"],
      ["Brian Brobbey", "ST", 23, 75, 81, "Netherlands"],
      ["Wilson Isidor", "ST", 24, 74, 79, "France"],
      ["Eliezer Mayenda", "ST", 20, 74, 82, "Spain"],
      ["Chemsdine Talbi", "RW", 20, 75, 83, "Morocco"],
      ["Noah Sadiki", "DM", 20, 74, 82, "Belgium"],
      ["Robin Roefs", "GK", 22, 74, 82, "Netherlands"],
      ["Trai Hume", "RB", 23, 75, 79, "Ireland"],
      ["Dan Ballard", "CB", 25, 75, 78, "Ireland"],
      ["Dennis Cirkin", "LB", 23, 74, 77, "England"],
      ["Chris Rigg", "CM", 18, 72, 86, "England"],
      ["Luke O'Nien", "CB", 30, 73, 73, "England"],
      ["Anthony Patterson", "GK", 25, 73, 76, "England"],
    ],
  },
  {
    name: "Tottenham Hotspur", abbrev: "TOT", stadium: "Tottenham Hotspur Stadium", colors: ["#FFFFFF", "#132257"], stature: 4, budget: 90,
    players: [
      ["Cristian Romero", "CB", 27, 85, 86, "Argentina"],
      ["Micky van de Ven", "CB", 24, 84, 88, "Netherlands"],
      ["Xavi Simons", "AM", 22, 84, 88, "Netherlands"],
      ["Dejan Kulusevski", "RW", 25, 83, 85, "Sweden"],
      ["Pedro Porro", "RB", 25, 82, 83, "Spain"],
      ["Mohammed Kudus", "RW", 25, 82, 84, "Ghana"],
      ["Guglielmo Vicario", "GK", 28, 82, 82, "Italy"],
      ["James Maddison", "AM", 28, 82, 82, "England"],
      ["João Palhinha", "DM", 30, 81, 81, "Portugal"],
      ["Destiny Udogie", "LB", 22, 80, 85, "Italy"],
      ["Dominic Solanke", "ST", 27, 80, 80, "England"],
      ["Pape Matar Sarr", "CM", 22, 80, 85, "Senegal"],
      ["Rodrigo Bentancur", "CM", 28, 80, 80, "Uruguay"],
      ["Lucas Bergvall", "CM", 19, 78, 88, "Sweden"],
      ["Richarlison", "ST", 28, 79, 79, "Brazil"],
      ["Yves Bissouma", "DM", 28, 79, 79, "Mali"],
      ["Wilson Odobert", "LW", 20, 76, 84, "France"],
      ["Kevin Danso", "CB", 26, 78, 79, "Austria"],
      ["Djed Spence", "RB", 25, 78, 80, "England"],
      ["Mathys Tel", "ST", 20, 76, 85, "France"],
      ["Archie Gray", "CM", 19, 76, 86, "England"],
      ["Randal Kolo Muani", "ST", 26, 80, 81, "France"],
      ["Antonín Kinský", "GK", 22, 75, 82, "Czech Republic"],
    ],
  },
  {
    name: "West Ham United", abbrev: "WHU", stadium: "London Stadium", colors: ["#7A263A", "#1BB1E7"], stature: 3, budget: 50,
    players: [
      ["Jarrod Bowen", "RW", 28, 83, 83, "England"],
      ["Lucas Paquetá", "AM", 27, 82, 83, "Brazil"],
      ["Alphonse Areola", "GK", 32, 79, 79, "France"],
      ["Aaron Wan-Bissaka", "RB", 27, 79, 79, "England"],
      ["Max Kilman", "CB", 28, 78, 78, "England"],
      ["Jean-Clair Todibo", "CB", 25, 78, 80, "France"],
      ["Crysencio Summerville", "LW", 23, 78, 84, "Netherlands"],
      ["Niclas Füllkrug", "ST", 32, 78, 78, "Germany"],
      ["Tomás Soucek", "CM", 30, 78, 78, "Czech Republic"],
      ["James Ward-Prowse", "CM", 30, 78, 78, "England"],
      ["Konstantinos Mavropanos", "CB", 27, 77, 77, "Greece"],
      ["El Hadji Malick Diouf", "LB", 20, 76, 84, "Senegal"],
      ["Mateus Fernandes", "CM", 21, 76, 83, "Portugal"],
      ["Soungoutou Magassa", "DM", 21, 75, 82, "France"],
      ["Callum Wilson", "ST", 33, 75, 75, "England"],
      ["Kyle Walker-Peters", "RB", 28, 77, 77, "England"],
      ["Mads Hermansen", "GK", 25, 77, 83, "Denmark"],
      ["Luis Guilherme", "RW", 19, 73, 84, "Brazil"],
      ["Oliver Scarles", "LB", 19, 72, 82, "England"],
    ],
  },
  {
    name: "Wolverhampton Wanderers", abbrev: "WOL", stadium: "Molineux", colors: ["#FDB913", "#231F20"], stature: 2, budget: 35,
    players: [
      ["João Gomes", "CM", 24, 80, 86, "Brazil"],
      ["Jørgen Strand Larsen", "ST", 25, 78, 82, "Norway"],
      ["José Sá", "GK", 32, 78, 78, "Portugal"],
      ["André", "DM", 24, 78, 84, "Brazil"],
      ["Jean-Ricner Bellegarde", "AM", 27, 77, 77, "France"],
      ["Emmanuel Agbadou", "CB", 28, 77, 77, "Ivory Coast"],
      ["Marshall Munetsi", "CM", 29, 76, 76, "Zimbabwe"],
      ["Santiago Bueno", "CB", 26, 76, 77, "Uruguay"],
      ["Jhon Arias", "RW", 27, 77, 78, "Colombia"],
      ["Hwang Hee-chan", "ST", 29, 76, 76, "South Korea"],
      ["Sam Johnstone", "GK", 32, 76, 76, "England"],
      ["Ladislav Krejcí", "CB", 26, 76, 78, "Czech Republic"],
      ["Toti Gomes", "CB", 26, 75, 76, "Portugal"],
      ["Jackson Tchatchoua", "RB", 23, 75, 80, "Cameroon"],
      ["Hugo Bueno", "LB", 22, 75, 80, "Spain"],
      ["Matt Doherty", "RB", 33, 74, 74, "Ireland"],
      ["Fer López", "AM", 21, 74, 83, "Spain"],
      ["Tolu Arokodare", "ST", 24, 75, 80, "Nigeria"],
      ["Jhon Mosquera", "RW", 25, 74, 78, "Colombia"],
      ["David Møller Wolfe", "LB", 23, 74, 79, "Norway"],
      ["Wesley Okoduwa", "LW", 18, 68, 82, "Nigeria"],
    ],
  },
];

// Pool of real EFL clubs used for promotion when Premier League sides are relegated.
// Squads are generated procedurally at promotion time (stature drives quality).
const PROMOTION_POOL = [
  { name: "Leicester City", abbrev: "LEI", stadium: "King Power Stadium", colors: ["#003090", "#FDBE11"], stature: 2 },
  { name: "Southampton", abbrev: "SOU", stadium: "St Mary's Stadium", colors: ["#D71920", "#FFFFFF"], stature: 2 },
  { name: "Ipswich Town", abbrev: "IPS", stadium: "Portman Road", colors: ["#0044A9", "#FFFFFF"], stature: 2 },
  { name: "Sheffield United", abbrev: "SHU", stadium: "Bramall Lane", colors: ["#EE2737", "#FFFFFF"], stature: 1 },
  { name: "Middlesbrough", abbrev: "MID", stadium: "Riverside Stadium", colors: ["#DE1B22", "#FFFFFF"], stature: 1 },
  { name: "Coventry City", abbrev: "COV", stadium: "CBS Arena", colors: ["#78D0F3", "#FFFFFF"], stature: 1 },
  { name: "West Bromwich Albion", abbrev: "WBA", stadium: "The Hawthorns", colors: ["#122F67", "#FFFFFF"], stature: 1 },
  { name: "Norwich City", abbrev: "NOR", stadium: "Carrow Road", colors: ["#00A650", "#FFF200"], stature: 1 },
  { name: "Stoke City", abbrev: "STK", stadium: "bet365 Stadium", colors: ["#E03A3E", "#FFFFFF"], stature: 1 },
  { name: "Blackburn Rovers", abbrev: "BLB", stadium: "Ewood Park", colors: ["#009EE0", "#FFFFFF"], stature: 1 },
  { name: "Watford", abbrev: "WAT", stadium: "Vicarage Road", colors: ["#FBEE23", "#ED2127"], stature: 1 },
  { name: "Hull City", abbrev: "HUL", stadium: "MKM Stadium", colors: ["#F5971D", "#000000"], stature: 1 },
  { name: "Bristol City", abbrev: "BRC", stadium: "Ashton Gate", colors: ["#E21A23", "#FFFFFF"], stature: 1 },
  { name: "Preston North End", abbrev: "PNE", stadium: "Deepdale", colors: ["#FFFFFF", "#1B4694"], stature: 1 },
];

if (typeof module !== "undefined") module.exports = { START_SEASON, REAL_TEAMS, PROMOTION_POOL };
