// Foreign clubs (non-playable leagues): transfer markets + Champions League guests.
// Format matches league teams. `euro: true` clubs can qualify for the Champions League.

const FOREIGN_CLUBS = [
  { name: "FC Porto", abbrev: "POR", country: "Portugal", euro: true, stadium: "Estádio do Dragão", colors: ["#00428C", "#FFFFFF"], stature: 3, budget: 40,
    players: [
      ["Diogo Costa", "GK", 25, 84, 88, "Portugal"],
      ["Alan Varela", "DM", 24, 80, 84, "Argentina"],
      ["Pepê", "RW", 28, 80, 80, "Brazil"],
      ["Samu Aghehowa", "ST", 21, 80, 86, "Spain"],
      ["Victor Froholdt", "CM", 19, 78, 85, "Denmark"],
      ["Jan Bednarek", "CB", 29, 76, 76, "Poland"],
      ["Gabri Veiga", "AM", 23, 78, 83, "Spain"],
      ["Francisco Moura", "LB", 26, 76, 78, "Portugal"],
      ["Nehuén Pérez", "CB", 25, 77, 80, "Argentina"],
      ["Borja Sainz", "LW", 24, 77, 81, "Spain"],
    ] },
  { name: "SL Benfica", abbrev: "BEN", country: "Portugal", euro: true, stadium: "Estádio da Luz", colors: ["#E30613", "#FFFFFF"], stature: 3, budget: 45,
    players: [
      ["Georgiy Sudakov", "AM", 23, 81, 86, "Ukraine"],
      ["Anatoliy Trubin", "GK", 24, 81, 86, "Ukraine"],
      ["Vangelis Pavlidis", "ST", 26, 80, 82, "Greece"],
      ["Richard Ríos", "DM", 25, 78, 82, "Colombia"],
      ["Kerem Aktürkoglu", "LW", 26, 78, 78, "Turkey"],
      ["Fredrik Aursnes", "CM", 29, 78, 78, "Norway"],
      ["Nicolás Otamendi", "CB", 37, 75, 75, "Argentina"],
      ["Dodi Lukébakio", "RW", 27, 79, 79, "Belgium"],
      ["Antonio Silva", "CB", 21, 79, 85, "Portugal"],
      ["Amar Dedic", "RB", 23, 77, 82, "Croatia"],
    ] },
  { name: "Sporting CP", abbrev: "SCP", country: "Portugal", euro: true, stadium: "José Alvalade", colors: ["#008151", "#FFFFFF"], stature: 3, budget: 40,
    players: [
      ["Pedro Gonçalves", "AM", 27, 82, 82, "Portugal"],
      ["Morten Hjulmand", "DM", 26, 80, 82, "Denmark"],
      ["Gonçalo Inácio", "CB", 24, 80, 84, "Portugal"],
      ["Francisco Trincão", "RW", 25, 79, 80, "Portugal"],
      ["Geovany Quenda", "RW", 18, 78, 89, "Portugal"],
      ["Luis Suárez Charris", "ST", 24, 79, 83, "Colombia"],
      ["Rui Silva", "GK", 31, 77, 77, "Portugal"],
      ["Ousmane Diomande", "CB", 21, 78, 84, "Ivory Coast"],
      ["Maxi Araújo", "LB", 25, 77, 79, "Uruguay"],
      ["Zeno Debast", "CB", 21, 77, 83, "Belgium"],
    ] },
  { name: "Ajax", abbrev: "AJX", country: "Netherlands", euro: true, stadium: "Johan Cruijff ArenA", colors: ["#D2122E", "#FFFFFF"], stature: 3, budget: 35,
    players: [
      ["Oscar Gloukh", "AM", 21, 78, 85, "Israel"],
      ["Kenneth Taylor", "CM", 23, 77, 81, "Netherlands"],
      ["Ko Itakura", "CB", 28, 77, 77, "Japan"],
      ["Kasper Dolberg", "ST", 27, 77, 77, "Denmark"],
      ["Mika Godts", "LW", 20, 77, 84, "Belgium"],
      ["Wout Weghorst", "ST", 33, 75, 75, "Netherlands"],
      ["Vitezslav Jaros", "GK", 24, 75, 80, "Czech Republic"],
      ["Josip Sutalo", "CB", 25, 76, 78, "Croatia"],
      ["Davy Klaassen", "CM", 32, 73, 73, "Netherlands"],
      ["Youri Baas", "CB", 22, 75, 80, "Netherlands"],
    ] },
  { name: "PSV Eindhoven", abbrev: "PSV", country: "Netherlands", euro: true, stadium: "Philips Stadion", colors: ["#ED1B2D", "#FFFFFF"], stature: 3, budget: 35,
    players: [
      ["Joey Veerman", "CM", 26, 79, 80, "Netherlands"],
      ["Jerdy Schouten", "DM", 28, 79, 79, "Netherlands"],
      ["Ismael Saibari", "AM", 24, 79, 83, "Morocco"],
      ["Ricardo Pepi", "ST", 22, 78, 83, "USA"],
      ["Ryan Flamingo", "CB", 22, 78, 84, "Netherlands"],
      ["Guus Til", "CM", 27, 77, 77, "Netherlands"],
      ["Dennis Man", "RW", 26, 77, 77, "Romania"],
      ["Matej Kovar", "GK", 25, 76, 79, "Czech Republic"],
      ["Yarek Gasiorowski", "CB", 20, 76, 83, "Spain"],
      ["Ivan Perisic", "LW", 36, 74, 74, "Croatia"],
    ] },
  { name: "Feyenoord", abbrev: "FEY", country: "Netherlands", euro: true, stadium: "De Kuip", colors: ["#E30613", "#FFFFFF"], stature: 2, budget: 30,
    players: [
      ["Quinten Timber", "CM", 24, 78, 83, "Netherlands"],
      ["Sem Steijn", "AM", 23, 77, 81, "Netherlands"],
      ["Ayase Ueda", "ST", 26, 76, 78, "Japan"],
      ["Anis Hadj Moussa", "RW", 23, 76, 82, "Algeria"],
      ["Tsuyoshi Watanabe", "CB", 26, 76, 76, "Japan"],
      ["Timon Wellenreuther", "GK", 29, 75, 75, "Germany"],
      ["Hugo Bueno II", "LB", 22, 74, 78, "Spain"],
      ["Luciano Valente", "CM", 21, 75, 82, "Netherlands"],
      ["Casper Tengstedt", "ST", 25, 75, 78, "Denmark"],
    ] },
  { name: "Celtic", abbrev: "CEL", country: "Scotland", euro: true, stadium: "Celtic Park", colors: ["#018749", "#FFFFFF"], stature: 2, budget: 28,
    players: [
      ["Daizen Maeda", "LW", 27, 77, 77, "Japan"],
      ["Reo Hatate", "CM", 27, 76, 76, "Japan"],
      ["Callum McGregor", "CM", 32, 74, 74, "Scotland"],
      ["Cameron Carter-Vickers", "CB", 27, 76, 76, "USA"],
      ["Arne Engels", "AM", 21, 75, 81, "Belgium"],
      ["Kasper Schmeichel", "GK", 38, 73, 73, "Denmark"],
      ["Benjamin Nygren", "RW", 24, 75, 77, "Sweden"],
      ["Kieran Tierney", "LB", 28, 76, 76, "Scotland"],
      ["Adam Idah", "ST", 24, 75, 78, "Ireland"],
      ["Anthony Ralston", "RB", 26, 73, 73, "Scotland"],
    ] },
  { name: "Rangers", abbrev: "RAN", country: "Scotland", euro: true, stadium: "Ibrox", colors: ["#0033A0", "#FFFFFF"], stature: 2, budget: 24,
    players: [
      ["James Tavernier", "RB", 33, 74, 74, "England"],
      ["Cyriel Dessers", "ST", 30, 74, 74, "Nigeria"],
      ["Nicolas Raskin", "CM", 24, 76, 80, "Belgium"],
      ["Mohamed Diomande", "CM", 23, 75, 79, "Ivory Coast"],
      ["Jack Butland", "GK", 32, 74, 74, "England"],
      ["John Souttar", "CB", 28, 74, 74, "Scotland"],
      ["Djeidi Gassama", "LW", 21, 74, 81, "France"],
      ["Findlay Curtis", "LW", 18, 72, 82, "Scotland"],
      ["Danilo Pereira", "ST", 26, 74, 76, "Brazil"],
    ] },
  { name: "Galatasaray", abbrev: "GAL", country: "Turkey", euro: true, stadium: "Rams Park", colors: ["#A32638", "#FDB912"], stature: 3, budget: 50,
    players: [
      ["Victor Osimhen", "ST", 26, 85, 87, "Nigeria"],
      ["Leroy Sané", "LW", 29, 82, 82, "Germany"],
      ["Ilkay Gündoğan", "CM", 34, 78, 78, "Germany"],
      ["Mauro Icardi", "ST", 32, 78, 78, "Argentina"],
      ["Uğurcan Çakır", "GK", 29, 79, 79, "Turkey"],
      ["Davinson Sánchez", "CB", 29, 78, 78, "Colombia"],
      ["Wilfried Singo", "CB", 24, 79, 83, "Ivory Coast"],
      ["Gabriel Sara", "CM", 26, 78, 81, "Brazil"],
      ["Barış Alper Yılmaz", "RW", 25, 78, 82, "Turkey"],
      ["Lucas Torreira", "DM", 29, 78, 78, "Uruguay"],
      ["Yunus Akgün", "RW", 25, 77, 79, "Turkey"],
    ] },
  { name: "Fenerbahçe", abbrev: "FEN", country: "Turkey", euro: true, stadium: "Şükrü Saracoğlu", colors: ["#FFED00", "#00205B"], stature: 3, budget: 45,
    players: [
      ["Ederson", "GK", 32, 84, 84, "Brazil"],
      ["Marco Asensio", "AM", 29, 79, 79, "Spain"],
      ["Youssef En-Nesyri", "ST", 28, 79, 79, "Morocco"],
      ["Jhon Durán", "ST", 21, 80, 85, "Colombia"],
      ["Milan Skriniar", "CB", 30, 79, 79, "Slovakia"],
      ["Anderson Talisca", "AM", 31, 77, 77, "Brazil"],
      ["Sebastian Szymanski", "AM", 26, 77, 78, "Poland"],
      ["Kerem Aktürkoğlu II", "LW", 26, 76, 76, "Turkey"],
      ["Archie Brown", "LB", 23, 76, 81, "England"],
      ["Nélson Semedo", "RB", 31, 76, 76, "Portugal"],
    ] },
  { name: "Besiktas", abbrev: "BES", country: "Turkey", euro: true, stadium: "Tüpraş Stadyumu", colors: ["#000000", "#FFFFFF"], stature: 2, budget: 30,
    players: [
      ["Tammy Abraham", "ST", 27, 78, 78, "England"],
      ["Rafa Silva", "AM", 32, 79, 79, "Portugal"],
      ["Wilfred Ndidi", "DM", 28, 77, 77, "Nigeria"],
      ["Jota Silva", "LW", 26, 76, 76, "Portugal"],
      ["Orkun Kökçü", "CM", 24, 78, 80, "Turkey"],
      ["Gabriel Paulista", "CB", 34, 73, 73, "Brazil"],
      ["Mert Günok", "GK", 26, 76, 76, "Turkey"],
      ["Taylan Bulut", "RB", 19, 74, 83, "Turkey"],
    ] },
  { name: "Club Brugge", abbrev: "CLB", country: "Belgium", euro: true, stadium: "Jan Breydel", colors: ["#0055A4", "#000000"], stature: 2, budget: 28,
    players: [
      ["Hans Vanaken", "CM", 33, 77, 77, "Belgium"],
      ["Christos Tzolis", "LW", 23, 78, 83, "Greece"],
      ["Raphael Onyedika", "DM", 24, 77, 81, "Nigeria"],
      ["Carlos Forbs", "RW", 21, 76, 83, "Portugal"],
      ["Nicolo Tresoldi", "ST", 21, 75, 82, "Germany"],
      ["Ludovit Reis", "CM", 25, 76, 78, "Netherlands"],
      ["Brandon Mechele", "CB", 32, 74, 74, "Belgium"],
      ["Nordin Jackers", "GK", 27, 74, 74, "Belgium"],
      ["Joel Ordoñez", "CB", 21, 77, 84, "Ecuador"],
      ["Romeo Vermant", "ST", 21, 75, 81, "Belgium"],
    ] },
  { name: "Olympiacos", abbrev: "OLY", country: "Greece", euro: true, stadium: "Karaiskakis", colors: ["#D6001C", "#FFFFFF"], stature: 2, budget: 26,
    players: [
      ["Ayoub El Kaabi", "ST", 32, 76, 76, "Morocco"],
      ["Daniel Podence", "LW", 29, 76, 76, "Portugal"],
      ["Santiago Hezze", "DM", 23, 76, 81, "Argentina"],
      ["Konstantinos Tzolakis", "GK", 22, 77, 84, "Greece"],
      ["Panagiotis Retsos", "CB", 27, 75, 75, "Greece"],
      ["Gelson Martins", "RW", 30, 74, 74, "Portugal"],
      ["Chiquinho", "AM", 29, 74, 74, "Portugal"],
      ["Charalampos Kostoulas II", "ST", 18, 73, 83, "Greece"],
    ] },
  { name: "RB Salzburg", abbrev: "SAL", country: "Austria", euro: true, stadium: "Red Bull Arena Salzburg", colors: ["#D50032", "#FFFFFF"], stature: 2, budget: 26,
    players: [
      ["Petar Ratkov", "ST", 21, 76, 83, "Serbia"],
      ["Maurits Kjaergaard", "CM", 22, 76, 82, "Denmark"],
      ["Mads Bidstrup", "DM", 24, 75, 78, "Denmark"],
      ["Alexander Schlager", "GK", 29, 75, 75, "Austria"],
      ["Yorbe Vertessen", "RW", 24, 75, 78, "Belgium"],
      ["Edmund Baidoo", "LW", 19, 74, 83, "Ghana"],
      ["Jacob Rasmussen", "CB", 28, 74, 74, "Denmark"],
      ["Frans Krätzig", "LB", 22, 74, 79, "Germany"],
    ] },
  { name: "Shakhtar Donetsk", abbrev: "SHK", country: "Ukraine", euro: true, stadium: "Arena Lviv", colors: ["#F36F21", "#000000"], stature: 2, budget: 26,
    players: [
      ["Dmytro Riznyk", "GK", 26, 76, 79, "Ukraine"],
      ["Artem Bondarenko", "AM", 22, 76, 82, "Ukraine"],
      ["Eguinaldo", "LW", 21, 75, 82, "Brazil"],
      ["Valeriy Bondar", "CB", 28, 74, 74, "Ukraine"],
      ["Kauã Elias", "ST", 19, 75, 84, "Brazil"],
      ["Marlon Gomes", "CM", 22, 75, 81, "Brazil"],
      ["Alisson Santana", "RW", 20, 74, 81, "Brazil"],
      ["Mykola Matviyenko", "CB", 29, 74, 74, "Ukraine"],
    ] },
  { name: "Al Nassr", abbrev: "ANS", country: "Saudi Arabia", stadium: "Al-Awwal Park", colors: ["#FFDD00", "#00205B"], stature: 3, budget: 90,
    players: [
      ["Cristiano Ronaldo", "ST", 40, 82, 82, "Portugal"],
      ["João Félix", "AM", 25, 79, 81, "Portugal"],
      ["Kingsley Coman", "LW", 29, 80, 80, "France"],
      ["Sadio Mané", "LW", 33, 78, 78, "Senegal"],
      ["Iñigo Martínez", "CB", 34, 78, 78, "Spain"],
      ["Marcelo Brozovic", "DM", 32, 77, 77, "Croatia"],
      ["Bento", "GK", 26, 78, 80, "Brazil"],
      ["Abdulrahman Ghareeb", "RW", 28, 73, 73, "Morocco"],
    ] },
  { name: "Al Hilal", abbrev: "AHL", country: "Saudi Arabia", stadium: "Kingdom Arena", colors: ["#0000CD", "#FFFFFF"], stature: 3, budget: 90,
    players: [
      ["Darwin Núñez", "ST", 26, 81, 83, "Uruguay"],
      ["Rúben Neves", "DM", 28, 81, 81, "Portugal"],
      ["Theo Hernández", "LB", 27, 80, 80, "France"],
      ["João Cancelo", "RB", 31, 79, 79, "Portugal"],
      ["Sergej Milinković-Savić", "CM", 30, 79, 79, "Serbia"],
      ["Aleksandar Mitrović", "ST", 30, 78, 78, "Serbia"],
      ["Yassine Bounou", "GK", 34, 78, 78, "Morocco"],
      ["Kalidou Koulibaly", "CB", 34, 76, 76, "Senegal"],
      ["Malcom", "RW", 28, 77, 77, "Brazil"],
    ] },
  { name: "Al Ittihad", abbrev: "ITT", country: "Saudi Arabia", stadium: "King Abdullah Sports City", colors: ["#FFD700", "#000000"], stature: 2, budget: 80,
    players: [
      ["Karim Benzema", "ST", 37, 79, 79, "France"],
      ["N'Golo Kanté", "DM", 34, 78, 78, "France"],
      ["Moussa Diaby", "RW", 26, 79, 79, "France"],
      ["Steven Bergwijn", "LW", 27, 76, 76, "Netherlands"],
      ["Houssem Aouar", "CM", 27, 75, 75, "Algeria"],
      ["Ahmed Al-Kassar", "GK", 28, 72, 72, "Morocco"],
    ] },
  { name: "Al Ahli", abbrev: "AHI", country: "Saudi Arabia", stadium: "Alinma Stadium", colors: ["#006B3F", "#FFFFFF"], stature: 2, budget: 80,
    players: [
      ["Riyad Mahrez", "RW", 34, 79, 79, "Algeria"],
      ["Ivan Toney", "ST", 29, 79, 79, "England"],
      ["Roberto Firmino", "ST", 33, 76, 76, "Brazil"],
      ["Franck Kessié", "CM", 28, 77, 77, "Ivory Coast"],
      ["Édouard Mendy", "GK", 33, 77, 77, "Senegal"],
      ["Merih Demiral", "CB", 27, 76, 76, "Turkey"],
    ] },
  { name: "Inter Miami", abbrev: "MIA", country: "USA", stadium: "Chase Stadium", colors: ["#F7B5CD", "#000000"], stature: 2, budget: 40,
    players: [
      ["Lionel Messi", "AM", 38, 84, 84, "Argentina"],
      ["Luis Suárez", "ST", 38, 72, 72, "Uruguay"],
      ["Sergio Busquets", "DM", 37, 73, 73, "Spain"],
      ["Rodrigo De Paul", "CM", 31, 79, 79, "Argentina"],
      ["Jordi Alba", "LB", 36, 72, 72, "Spain"],
      ["Tadeo Allende", "RW", 26, 74, 74, "Argentina"],
      ["Oscar Ustari", "GK", 39, 68, 68, "Argentina"],
      ["Benjamin Cremaschi", "CM", 20, 74, 81, "USA"],
    ] },
  { name: "LA Galaxy", abbrev: "LAG", country: "USA", stadium: "Dignity Health Sports Park", colors: ["#00245D", "#FFD200"], stature: 1, budget: 25,
    players: [
      ["Marco Reus", "AM", 36, 75, 75, "Germany"],
      ["Gabriel Pec", "RW", 24, 76, 79, "Brazil"],
      ["Joseph Paintsil", "LW", 27, 75, 75, "Ghana"],
      ["Riqui Puig", "CM", 25, 77, 79, "Spain"],
      ["Maya Yoshida", "CB", 36, 69, 69, "Japan"],
    ] },
  { name: "LAFC", abbrev: "LAF", country: "USA", stadium: "BMO Stadium", colors: ["#000000", "#C39E6D"], stature: 2, budget: 30,
    players: [
      ["Son Heung-min", "ST", 33, 82, 82, "South Korea"],
      ["Denis Bouanga", "LW", 30, 77, 77, "Gabon"],
      ["Hugo Lloris", "GK", 38, 74, 74, "France"],
      ["Mark Delgado", "CM", 30, 72, 72, "USA"],
      ["Ryan Hollingshead", "LB", 34, 70, 70, "USA"],
    ] },
  { name: "Flamengo", abbrev: "FLA", country: "Brazil", stadium: "Maracanã", colors: ["#C52613", "#000000"], stature: 3, budget: 35,
    players: [
      ["Pedro", "ST", 28, 79, 79, "Brazil"],
      ["Giorgian de Arrascaeta", "AM", 31, 79, 79, "Uruguay"],
      ["Jorginho", "DM", 33, 77, 77, "Italy"],
      ["Nicolás de la Cruz", "CM", 28, 77, 77, "Uruguay"],
      ["Agustín Rossi", "GK", 30, 76, 76, "Argentina"],
      ["Léo Ortiz", "CB", 29, 75, 75, "Brazil"],
      ["Luiz Araújo", "RW", 29, 75, 75, "Brazil"],
      ["Samuel Lino", "LW", 25, 77, 79, "Brazil"],
      ["Danilo", "CB", 34, 74, 74, "Brazil"],
    ] },
  { name: "Palmeiras", abbrev: "PAM", country: "Brazil", stadium: "Allianz Parque", colors: ["#006437", "#FFFFFF"], stature: 3, budget: 35,
    players: [
      ["Vitor Roque", "ST", 20, 78, 85, "Brazil"],
      ["José Manuel López", "ST", 24, 77, 80, "Argentina"],
      ["Raphael Veiga", "AM", 30, 77, 77, "Brazil"],
      ["Weverton", "GK", 37, 74, 74, "Brazil"],
      ["Gustavo Gómez", "CB", 30, 76, 76, "Paraguay"],
      ["Andreas Pereira", "CM", 29, 77, 77, "Brazil"],
      ["Ramón Sosa", "LW", 26, 75, 77, "Paraguay"],
      ["Bruno Fuchs", "CB", 26, 74, 74, "Brazil"],
    ] },
  { name: "River Plate", abbrev: "RIV", country: "Argentina", stadium: "Monumental", colors: ["#FFFFFF", "#EB1C2D"], stature: 2, budget: 25,
    players: [
      ["Sebastián Driussi", "ST", 29, 75, 75, "Argentina"],
      ["Miguel Borja", "ST", 32, 74, 74, "Colombia"],
      ["Juan Fernando Quintero", "AM", 32, 75, 75, "Colombia"],
      ["Franco Armani", "GK", 38, 71, 71, "Argentina"],
      ["Lucas Martínez Quarta", "CB", 29, 75, 75, "Argentina"],
      ["Kevin Castaño", "CM", 24, 75, 79, "Colombia"],
      ["Ian Subiabre", "RW", 18, 73, 84, "Argentina"],
    ] },
  { name: "Boca Juniors", abbrev: "BOC", country: "Argentina", stadium: "La Bombonera", colors: ["#003B94", "#F8B300"], stature: 2, budget: 25,
    players: [
      ["Leandro Paredes", "DM", 31, 78, 78, "Argentina"],
      ["Edinson Cavani", "ST", 38, 73, 73, "Uruguay"],
      ["Miguel Merentiel", "ST", 29, 74, 74, "Uruguay"],
      ["Exequiel Zeballos", "RW", 23, 75, 80, "Argentina"],
      ["Carlos Palacios", "AM", 25, 75, 78, "Chile"],
      ["Agustín Marchesín", "GK", 37, 72, 72, "Argentina"],
      ["Ayrton Costa", "CB", 26, 74, 74, "Argentina"],
    ] },
  { name: "Santos", abbrev: "SAN", country: "Brazil", stadium: "Vila Belmiro", colors: ["#FFFFFF", "#000000"], stature: 2, budget: 22,
    players: [
      ["Neymar", "LW", 33, 80, 80, "Brazil"],
      ["Guilherme", "LW", 29, 74, 74, "Brazil"],
      ["Tiquinho Soares", "ST", 34, 73, 73, "Brazil"],
      ["Gabriel Brazão", "GK", 24, 75, 79, "Brazil"],
      ["Zé Rafael", "CM", 32, 73, 73, "Brazil"],
      ["Luan Peres", "CB", 31, 72, 72, "Brazil"],
    ] },
  { name: "Corinthians", abbrev: "CTH", country: "Brazil", stadium: "Neo Química Arena", colors: ["#000000", "#FFFFFF"], stature: 2, budget: 22,
    players: [
      ["Memphis Depay", "ST", 31, 77, 77, "Netherlands"],
      ["Yuri Alberto", "ST", 24, 76, 79, "Brazil"],
      ["Rodrigo Garro", "AM", 27, 76, 76, "Argentina"],
      ["Hugo Souza", "GK", 26, 75, 77, "Brazil"],
      ["André Ramalho", "CB", 33, 72, 72, "Brazil"],
      ["Breno Bidon", "CM", 20, 74, 82, "Brazil"],
    ] },
  { name: "Botafogo", abbrev: "BOT", country: "Brazil", stadium: "Nilton Santos", colors: ["#000000", "#FFFFFF"], stature: 2, budget: 22,
    players: [
      ["Jefferson Savarino", "AM", 28, 75, 75, "Colombia"],
      ["John Victor II", "GK", 29, 75, 75, "Brazil"],
      ["Alexander Barboza", "CB", 30, 75, 75, "Argentina"],
      ["Artur", "RW", 27, 75, 75, "Brazil"],
      ["Marlon Freitas", "DM", 30, 74, 74, "Brazil"],
      ["Álvaro Montoro", "AM", 18, 73, 84, "Argentina"],
    ] },
];

if (typeof module !== "undefined") module.exports = { FOREIGN_CLUBS };
